name: vehicle_tracker
repository: https://github.com/abinashk/vehicle-tracker

packages:
  - packages/**
  - apps/**

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  analyze:
    run: dart analyze --fatal-infos
    exec:
      concurrency: 3
    description: Run dart analyze in all packages

  test:
    run: flutter test
    exec:
      concurrency: 1
      failFast: true
    packageFilters:
      dirExists: test
    description: Run tests in all packages

  format:
    run: dart format --set-exit-if-changed .
    description: Check formatting in all packages

  clean:
    run: flutter clean
    exec:
      concurrency: 3
    description: Clean all packages
